name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]     # despliega en cada push a main
  workflow_dispatch:        # puedes lanzarlo a mano desde Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: hosting-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Vite
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.7.2
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KYTRON_APPS }}
          PROJECT_ID: kytron-apps